"use client"

// 

import React from 'react';
import Image from 'next/image'
import WaitlistForm from '../_components/WaitlistForm';
import AutoTyper from '../_components/AutoTyper';
import AutoTyperNL from '../_components/AutoTyperNL';
import CTABanner from '../_components/CTABanner';

// export const metadata = {
//   title: 'Nauvis',
//   description: 'unlock data-driven business foresight ',
// }


export default function Home() {
  return (
    <main className="">
      <div className="grid grid-cols-1 gap-12 lg:gap-16 text-center justify-items-center py-10 lg:py-28 px-10 lg:px-24">
        <div className="prose lg:prose-2xl text-cont">
          <h1>
            global enterprise solutions that <br />
            <span className='underline decoration-highlight'>
              <AutoTyper
                typeArray={[
                  "identify new trade opportunities",
                  "anticipate regulatory impacts",
                  "predict supply chain disruptions",
                  "optimize sourcing strategies",
                  "sharpen investment decisions",
                  "size addressable markets",
                  "tailor regional entry",
                  "personalize product offerings",
                  "forecast trade flows",
                  "uncover hidden risks",
                  "visualize complex dynamics",
                  "simplify scenario planning",
                  "structure disparate data",
                  "contextualize news signals",
                  "benchmark performance",
                  "map supply dependencies",
                  "strengthen trade partnerships",
                  "confidently navigate uncertainty",
                  "continuously realign strategies"
                ]}
              />
            </span>
          </h1>
          <p className="text-base">nauvis aggregates and analyzes complex global trade data into intuitive visualizations and predictive models, empowering organizations to confidently navigate uncertainty and capitalize on risks and opportunities.</p>
          <div className='justify-items-center'><WaitlistForm alignSelf={"center"} /></div>
        </div>
        <div className="grid grid-cols-1 justify-items-center">
          <video className="border border-light w-full lg:w-2/3 rounded-[20px]" src='./Nauvis-Showcase.mp4' controls="controls" />
        </div>
      </div>
      <div>
        {/* Desktop */}
        <div className='hidden lg:block'>
          <div className="grid grid-cols-2 gap-8 lg:gap-16 lg:gap-y-24 text-left justify-items-left bg-bg2 py-12 lg:py-32 px-10 lg:px-24">
            <div className="col-span-1 col-start-1 sticky top-60 h-fit mb-10">
              <div className="prose lg:prose-2xl">
                <h1 className='font-medium'>
                  <AutoTyperNL typeArray={['value proposition']} />
                </h1>
              </div>
              <br />
              <br />
              <div className="prose lg:prose-2xl">
                <p className="text-base"> in a world where escalating trade wars, shifting policies, and supply chain volatility lead to $4 trillion in impacted trade annually, nauvis emerges as a revolutionary solution, empowering trade teams globally to enhance outcomes through predictive intelligence and data-driven clarity across markets.  </p>
              </div>
            </div>
            <div className="col-span-1 col-start-2">
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-12 mb-20">
                <h3 className="mt-2">comprehensive integrated analytics</h3>
                <p className="text-base text-bg2">with the capability to process insights across billions of trade data points, nauvis offers unparalleled cross-domain visibility tailored to organizational needs across sectors.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-12 mb-20">
                <h3>quantified forward-looking insights</h3>

                <p className="text-base text-bg2">armed with extensive modeled scenarios generated by nauvis, trade teams can execute market strategies that are predictive instead of reactive based on industry-specific intelligence.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-12 mb-20">
                <h3>focus on early risk identification</h3>
                <p className="text-base text-bg2">navigating complex trade ecosystems requires identifying early signals amidst noise. nauvis translates leading indicators into quantitative insights to drive decisive action.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-12 mb-20">
                <h3>measurable competitive advantage</h3>
                <p className="text-base text-bg2">volatile trade conditions contribute to approximately $500 billion in direct and indirect losses annually. with nauvis, trade leaders can achieve significant savings, optimize planning, and respond quickly to market shifts.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-12 mb-20">
                <h3>interconnected data foundation</h3>
                <p className="text-base text-bg2">we aggregate disparate trade data spanning flows, logistics, policy news and more. our cloud data platform then identifies relationships across datasets using ai to quantify risks and upside for strategic planning.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-12">
                <h3>predictive scenario modeling</h3>
                <p className="text-base text-bg2">our automated models simulate policy shifts, demand changes, shipping dislocations and other variables in tandem to output tailored insights on probabilistic market scenarios — arming clients with intelligence to evaluate options.</p>
              </div>
            </div>
          </div>
          <div className='hidden lg:block'>
            <div className="grid grid-cols-2 gap-8 lg:gap-16 lg:gap-y-24 text-left justify-items-left bg-bg2 py-12 lg:py-32 px-10 lg:px-24 content-center place-content-center place-items-center">
              <Image
                className='col-span-1 rounded-[40px] shadow-sm shadow-dark'
                src="/flight_vectorz.png"
                alt="Flight Picture Vectorized"
                sizes="100vw"
                style={{
                  width: '100%',
                  height: 'auto',
                }}
                width={1000}
                height={1125}
              />
              <div className='col-span-1 prose lg:prose-2xl place-self-center'>
                <h2 className="font-light">pushing innovation in global trade</h2>
                <p className='text-base'>nauvis leverages integrated data and intelligent analytics to enable organizations to confidently navigate risks and optimize opportunities in dynamic global trade ecosystems.
                  <br />
                  <br />
                  by mapping interdependencies between market forces, we facilitate proactive scenario planning grounded in science not speculation. our models surface early signals prompting decisive action tailored to each customer's context.
                  <br />
                  <br />
                  the result is competitive advantage through the ability to smoothly pivot strategies, ensure resilient operations, and responsibly enter new markets.
                </p>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-8 lg:gap-16 lg:gap-y-24 text-left justify-items-left bg-dark py-12 lg:py-32 px-10 lg:px-24">
            <div className="prose lg:prose-2xl col-span-2 max-w-7xl prose-invert">
              <h1 className='font-medium'>
                <AutoTyperNL typeArray={['our solutions']} />
              </h1>
            </div>
            <div className="col-span-2 grid grid-cols-4 grid-rows-2 gap-6 w-full">
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">supply chain mapping</h3>
                <p className="text-base text-dark">visually trace multi-tier supply chains across geographies to uncover risks, optimize flows, and model what-if scenarios.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">logistics forecasting</h3>
                <p className="text-base text-dark">access forecasts quantifying delays, rate volatility, and carrier capacity constraints to inform transport procurement and inventory decisions.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">trade policy analysis</h3>
                <p className="text-base text-dark">model trade agreement, tariff policy and non-tariff measure scenario impacts on specific country-product trade flows for contingency planning.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">macro trend analytics</h3>
                <p className="text-base text-dark">interactive tools to decompose bilateral trade drivers across economic factors like income, demographics and commodity dependence.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">early warning system</h3>
                <p className="text-base text-dark">machine learning pattern recognition to rapidly detect supply chain anomalies, negative regulatory shifts, and trade flow disruptions.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">competitive benchmarking</h3>
                <p className="text-base text-dark">compare your company's global trade performance across dimensions like market share, costs and policy exposure versus industry peers.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">customer trade profile</h3>
                <p className="text-base text-dark">upload your company's imports, exports, carriers and products data to generate tailored insights, predictions and recommendations unique to your trade flows.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-12 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">ecosystem integrations</h3>
                <p className="text-base text-dark">access nauvis data, insights and analytical models via APIs and embeddings for integration into your BI tools, ERP platform and custom applications.</p>
              </div>

            </div>
          </div>
        </div>
        {/* Mobile */}
        <div className='block lg:hidden'>
          <div className="grid grid-cols-2 gap-8 lg:gap-16 lg:gap-y-24 text-left justify-items-left bg-bg2 py-12 lg:py-32 px-10 lg:px-24">
            <div className="col-span-2 col-start-1 h-fit mb-4">
              <div className="prose lg:prose-2xl">
                <h1 className='font-medium'>
                  <AutoTyperNL typeArray={['value proposition']} />
                </h1>
              </div>
              <br />
              <br />
              <div className="prose lg:prose-2xl">
                <p className="text-base"> in a world where escalating trade wars, shifting policies, and supply chain volatility lead to $4 trillion in impacted trade annually, nauvis emerges as a revolutionary solution, empowering trade teams globally to enhance outcomes through predictive intelligence and data-driven clarity across markets.  </p>
              </div>
            </div>
            <div className="col-span-2">
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-8 pt-6 mb-10">
                <h3 className="mt-2">comprehensive integrated analytics</h3>
                <p className="text-base text-bg2">with the capability to process insights across billions of trade data points, nauvis offers unparalleled cross-domain visibility tailored to organizational needs across sectors.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-8 pt-6 mb-10">
                <h3>quantified forward-looking insights</h3>
                <p className="text-base text-bg2">armed with extensive modeled scenarios generated by nauvis, trade teams can execute market strategies that are predictive instead of reactive based on industry-specific intelligence.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-8 pt-6 mb-10">
                <h3>focus on early risk identification</h3>
                <p className="text-base text-bg2">navigating complex trade ecosystems requires identifying early signals amidst noise. nauvis translates leading indicators into quantitative insights to drive decisive action.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-8 pt-6 mb-10">
                <h3>measurable competitive advantage</h3>
                <p className="text-base text-bg2">volatile trade conditions contribute to approximately $500 billion in direct and indirect losses annually. with nauvis, trade leaders can achieve significant savings, optimize planning, and respond quickly to market shifts.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-8 pt-6 mb-10">
                <h3>interconnected data foundation</h3>
                <p className="text-base text-bg2">we aggregate disparate trade data spanning flows, logistics, policy news and more. our cloud data platform then identifies relationships across datasets using ai to quantify risks and upside for strategic planning.</p>
              </div>
              <div className="bg-highlight prose prose-invert lg:prose-2xl rounded-[20px] p-8 pt-6">
                <h3>predictive scenario modeling</h3>
                <p className="text-base text-bg2">our automated models simulate policy shifts, demand changes, shipping dislocations and other variables in tandem to output tailored insights on probabilistic market scenarios — arming clients with intelligence to evaluate options.</p>
              </div>
            </div>
          </div>
          <hr className="rounded max-w-[90%] mr-[5%] ml-[5%] opacity-10"></hr>
          <div className=''>
            <div className="grid grid-cols-2 gap-8 lg:gap-16 lg:gap-y-24 text-left justify-items-left bg-bg2 py-12 lg:py-32 px-10 lg:px-24 content-center place-content-center place-items-center">
              <Image
                className='col-span-2 rounded-[20px] shadow-sm shadow-dark'
                src="/flight_vectorz.png"
                alt="Flight Picture Vectorized"
                sizes="100vw"
                style={{
                  width: '100%',
                  height: 'auto',
                }}
                width={1000}
                height={1125}
              />
              <div className='col-span-2 prose lg:prose-2xl place-self-center'>
                <h2 className="font-base">pushing innovation in global trade</h2>
                <p className='text-base'>nauvis leverages integrated data and intelligent analytics to enable organizations to confidently navigate risks and optimize opportunities in dynamic global trade ecosystems.
                  <br />
                  <br />
                  by mapping interdependencies between market forces, we facilitate proactive scenario planning grounded in science not speculation. our models surface early signals prompting decisive action tailored to each customer's context.
                  <br />
                  <br />
                  the result is competitive advantage through the ability to smoothly pivot strategies, ensure resilient operations, and responsibly enter new markets.
                </p>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-8 lg:gap-16 lg:gap-y-24 text-left justify-items-left bg-dark py-12 lg:py-32 px-10 lg:px-24">
            <div className="prose lg:prose-2xl col-span-2 max-w-7xl prose-invert">
              <h1 className='font-medium'>
                <AutoTyperNL typeArray={['our solutions']} />
              </h1>
            </div>
            <div className="col-span-2 grid grid-cols-1 gap-6 w-full">
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">supply chain mapping</h3>
                <p className="text-base text-dark">visually trace multi-tier supply chains across geographies to uncover risks, optimize flows, and model what-if scenarios.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">logistics forecasting</h3>
                <p className="text-base text-dark">access forecasts quantifying delays, rate volatility, and carrier capacity constraints to inform transport procurement and inventory decisions.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">trade policy analysis</h3>
                <p className="text-base text-dark">model trade agreement, tariff policy and non-tariff measure scenario impacts on specific country-product trade flows for contingency planning.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">macro trend analytics</h3>
                <p className="text-base text-dark">interactive tools to decompose bilateral trade drivers across economic factors like income, demographics and commodity dependence.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">early warning system</h3>
                <p className="text-base text-dark">machine learning pattern recognition to rapidly detect supply chain anomalies, negative regulatory shifts, and trade flow disruptions.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">competitive benchmarking</h3>
                <p className="text-base text-dark">compare your company's global trade performance across dimensions like market share, costs and policy exposure versus industry peers.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">customer trade profile</h3>
                <p className="text-base text-dark">upload your company's imports, exports, carriers and products data to generate tailored insights, predictions and recommendations unique to your trade flows.</p>
              </div>
              <div className="bg-bg2 rounded-[20px] p-8 prose lg:prose-2xl prose-invert hover:scale-105">
                <h3 className="text-highlight2">ecosystem integrations</h3>
                <p className="text-base text-dark">access nauvis data, insights and analytical models via APIs and embeddings for integration into your BI tools, ERP platform and custom applications.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
